name: firebase_chat
description: Fully functional package for Cloud Firestore that makes easier to implement chat in your application
version: 0.0.3
homepage: https://github.com/tedcrimson/firebase_chat

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  cloud_firestore: ^0.16.0
  cached_network_image: ^2.5.0
  http: ^0.12.2
  intl: ^0.16.1
  firestore_repository: ^0.0.1+2
  firebase_storage_repository: ^0.0.2+3
    # path: ../firebase_storage_repository
  gallery_previewer: ^0.0.1+1
    # path: ../gallery_previewer
    # git:
    #   url: git@github.com:tedcrimson/packages.git
    #   path: gallery_previewer
