name: firebase_chat
description: Fully functional package for Cloud Firestore that makes easier to implement chat in your application
version: 0.0.1
homepage: https://github.com/tedcrimson/firebase_chat

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  firestore_repository:
    # path: ../firestore_repository
    git:
      url: git@github.com:tedcrimson/packages.git
      path: firestore_repository
  firebase_storage_repository:
    # path: ../firebase_storage_repository
    git:
      url: git@github.com:tedcrimson/packages.git
      path: firebase_storage_repository
  user_repository:
    # path: ../packages/user_repository
    git:
      url: git@github.com:tedcrimson/packages.git
      path: user_repository
  gallery_previewer:
    # path: ../gallery_previewer
    git:
      url: git@github.com:tedcrimson/packages.git
      path: gallery_previewer
